name: Build on Windows with MSYS2

on:
  push:
    branches: [ "devel", "master" ]
  pull_request:
    branches: [ "devel", "master" ]
  workflow_dispatch:

env:
  BUILD_TYPE: RelWithDebInfo
  INSTALL_LOCATION: SonivoxEAS
  DRUMSTICK: DrumstickV2

jobs:
  build:
    runs-on: windows-latest
    strategy:
        fail-fast: false
        matrix:
          include:
            # { icon: '⬛', sys: mingw32 } # There are no 32 bit packages for Qt6 in msys2 anymore
            - { icon: '🟦', sys: mingw64 }
            - { icon: '🟨', sys: ucrt64  }
            - { icon: '🟧', sys: clang64 }
            - { icon: '🟩', sys: clangarm64 }
    name: 🚧${{ matrix.icon }} ${{ matrix.sys }}
    defaults:
      run:
        shell: msys2 {0}

    steps:
    - name: '${{ matrix.icon }} Setup MSYS2'
      uses: msys2/setup-msys2@v2
      with:
        release: false
        update: true
        msystem: ${{matrix.sys}}
        install: >-
          git
          make
        pacboy: >-
          toolchain:p
          cmake:p
          ninja:p
          qt6-base:p
          qt6-tools:p
          qt6-translations:p
          qt6-multimedia:p
          sonivox:p

    - name: '${{ matrix.icon }} Install NSIS'
      uses: repolevedavaj/install-nsis@v1.1.0
      with:
        nsis-version: '3.11'

    - name: '${{ matrix.icon }} Checkout'
      uses: actions/checkout@v4

    - name: '${{ matrix.icon }} Download Drumstick'
      uses: dawidd6/action-download-artifact@v11
      with:
        name: ${{env.DRUMSTICK}}-${{matrix.sys}}
        github_token: ${{secrets.GH_PAT}}
        repo: pedrolcl/drumstick
        allow_forks: false
        workflow: cmake-win.yml
        branch: devel

    - name: '${{ matrix.icon }} Extract Drumstick'
      run: tar xvf ${{env.DRUMSTICK}}.tar

    - name: '${{ matrix.icon }} Configure CMake'
      id: configuration
      run: >
        cmake -B build
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        -DCMAKE_PREFIX_PATH="${{env.DRUMSTICK}}"
        -DCMAKE_INSTALL_PREFIX=${{env.INSTALL_LOCATION}}
        -DDEPENDENCY_DIRS="${{env.DRUMSTICK}}"

    - name: '${{ matrix.icon }} Build'
      run: cmake --build build --config ${{env.BUILD_TYPE}}

    - name: '${{ matrix.icon }} Package'
      run: cmake --build build --target package

    - name: '${{ matrix.icon }} Upload artifact'
      uses: actions/upload-artifact@v6
      with:
        name: windows-installer
        path: ${{github.workspace}}/build/sonivoxeas-${{steps.configuration.outputs.config_version}}-${{matrix.sys}}.exe
        retention-days: 90
        overwrite: true
